// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6jsM6NXjHJcZdqCCpJuDOw2zQMa0BOk0',
    appId: '1:1002393617077:web:acc6cb5dd35e901337f4fc',
    messagingSenderId: '1002393617077',
    projectId: 'confio-394116',
    authDomain: 'confio-394116.firebaseapp.com',
    storageBucket: 'confio-394116.appspot.com',
    measurementId: 'G-29ZNWN8MHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqQB4Xlk4CXvjh7qVuz9GLfQqP2GEvU1c',
    appId: '1:1002393617077:android:bb8ffeee1a9df1f137f4fc',
    messagingSenderId: '1002393617077',
    projectId: 'confio-394116',
    storageBucket: 'confio-394116.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVDh5fsz2b_IDa1rNvAs_ENXQYw5p0j0o',
    appId: '1:1002393617077:ios:cd56c762430522b337f4fc',
    messagingSenderId: '1002393617077',
    projectId: 'confio-394116',
    storageBucket: 'confio-394116.appspot.com',
    androidClientId: '1002393617077-ljs0qjufns6aa29t2ip0uu6jq4ljqn8e.apps.googleusercontent.com',
    iosClientId: '1002393617077-c7cnerubbi5o07gb3t001hg6q140qg8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.confio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVDh5fsz2b_IDa1rNvAs_ENXQYw5p0j0o',
    appId: '1:1002393617077:ios:307a2b90247763d437f4fc',
    messagingSenderId: '1002393617077',
    projectId: 'confio-394116',
    storageBucket: 'confio-394116.appspot.com',
    androidClientId: '1002393617077-ljs0qjufns6aa29t2ip0uu6jq4ljqn8e.apps.googleusercontent.com',
    iosClientId: '1002393617077-2ebn6pjcebrb72tj85akevopli5uskg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.confio.RunnerTests',
  );
}
